version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: kds-mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: KDS
    networks:
      - kds-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  kds-api:
    build:
      context: .
      dockerfile: src/kdspro.Api/Dockerfile
    container_name: kds-backend
    restart: always
    ports:
      - "5162:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MongoDB__ConnectionString=mongodb://admin:secret@mongodb:27017
      - MongoDB__DatabaseName=KDS
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - kds-network

volumes:
  mongo_data:

networks:
  kds-network:
