services:
  mongodb:
    image: mongo:8.0
    container_name: kds-mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    networks:
      - kds-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  kds-api:
    build:
      context: .
      dockerfile: kdspro.Api/Dockerfile  
    container_name: kds-backend
    restart: always
    ports:
      - "5162:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MongoDB__ConnectionString=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB}?authSource=admin
      - MongoDB__DatabaseName=KDS
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=kds-api
      - Jwt__Audience=kds-client
    networks:
      - kds-network

volumes:
  mongo_data:

networks:
  kds-network:
   driver: bridge
