services:
  mongodb:
    image: mongo:latest
    container_name: kds-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: KdsDatabase

volumes:
  mongo_data: